services:
  lerndex:
    build: .
    restart: unless-stopped
    volumes:
      - db_data:/app/lerndex.db
    environment:
      - PORT=80
    networks:
      - web
    labels:
      caddy: lerndex-janik.hackerwerkstatt.de
      caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  db_data:

networks:
  web:
    external: true
